# turns the webui files into a C++ header of raw string literals
# invoked at build time from the root CMakeLists

function(embed_file var path)
    file(READ "${path}" content)
    set(${var} "${content}" PARENT_SCOPE)
endfunction()

embed_file(INDEX_HTML "${WEBUI_DIR}/index.html")
embed_file(STYLE_CSS  "${WEBUI_DIR}/style.css")
embed_file(APP_JS     "${WEBUI_DIR}/app.js")

set(DELIM "BREEZE_RAW")

file(WRITE  "${OUT_HEADER}" "// generated by cmake/embed_webui.cmake, do not edit\n")
file(APPEND "${OUT_HEADER}" "#pragma once\n\n")
file(APPEND "${OUT_HEADER}" "namespace breeze_webui {\n\n")
file(APPEND "${OUT_HEADER}" "inline const char * index_html = R\"${DELIM}(${INDEX_HTML})${DELIM}\";\n\n")
file(APPEND "${OUT_HEADER}" "inline const char * style_css = R\"${DELIM}(${STYLE_CSS})${DELIM}\";\n\n")
file(APPEND "${OUT_HEADER}" "inline const char * app_js = R\"${DELIM}(${APP_JS})${DELIM}\";\n\n")
file(APPEND "${OUT_HEADER}" "}\n")
